/* ═══════════════════════════════════════════
   GameStore — каталог товаров (демо-данные)
   Все цены в USD (базовая валюта)
   gradient: цвета для градиента-заглушки вместо реальной картинки
   ═══════════════════════════════════════════ */

const GAMES = [
  {
    id: 1,
    title: { ru: 'Аккаунт Steam + 50 игр', en: 'Steam Account + 50 Games' },
    short: { ru: 'CS2, GTA, Rust и ещё 47 игр', en: 'CS2, GTA, Rust + 47 more' },
    platform: 'Steam',
    genres: ['shooter', 'rpg', 'racing'],
    type: ['games'],
    region: 'ru',
    price: 29.99,
    oldPrice: null,
    rating: 4.8,
    reviews: 214,
    sold: 312,
    added: 12,
    updated: 3,
    emoji: '🎮',
    gradient: ['#0E5C2F', '#1AA64B'],
    badge: 'new',
    features: { ru: ['24 игры · 340 ч наиграно', 'Почта сменяемая', 'Оригинальный владелец'], en: ['24 games · 340 hrs played', 'Email changeable', 'Original owner'] },
    desc: {
      ru: 'Прокачанный аккаунт Steam с большой библиотекой: Counter-Strike 2 с Prime-статусом, GTA V, Rust, Elden Ring и другие хиты. Уровень профиля 27, есть часы в играх. Аккаунт чистый, без блокировок и VAC-банов. Первичный владелец, полная почта в комплекте — смените данные на свои и играйте.',
      en: 'Leveled Steam account with a big library: Counter-Strike 2 with Prime, GTA V, Rust, Elden Ring and more hits. Profile level 27, hours in games. Clean account, no bans. Original owner, full email included.'
    },
    media: [
      { emoji: '🎮', type: 'video', dur: '1:24' },
      { emoji: '🕹️', type: 'img' },
      { emoji: '📦', type: 'img' },
      { emoji: '🎯', type: 'img' },
    ],
  },
  {
    id: 2,
    title: { ru: 'CS2 Prime + редкие скины', en: 'CS2 Prime + Rare Skins' },
    short: { ru: 'Prime-статус, 12 скинов в инвентаре', en: 'Prime status, 12 skins in inventory' },
    platform: 'Steam',
    genres: ['shooter'],
    type: ['skins', 'rank'],
    region: 'eu',
    price: 15.49,
    oldPrice: 21.99,
    rating: 4.9,
    reviews: 187,
    sold: 298,
    added: 9,
    updated: 1,
    emoji: '🎯',
    gradient: ['#4A148C', '#7B1FA2'],
    badge: 'new',
    features: {
      ru: ['Prime-статус активен', 'AK-47 Redline, AWP Asiimov', 'Ранг Legendary Eagle'],
      en: ['Prime status active', 'AK-47 Redline, AWP Asiimov', 'Legendary Eagle rank'],
    },
    desc: {
      ru: 'Аккаунт CS2 с Prime-статусом и инвентарём из 12 скинов, включая AK-47 Redline, AWP Asiimov и нож-бабочку в износе Field-Tested. Ранг Legendary Eagle Master. Хорошая статистика K/D. Почта сменяемая, гарантия 30 дней.',
      en: 'CS2 account with Prime and 12 skins including AK-47 Redline, AWP Asiimov and a Field-Tested Butterfly Knife. Legendary Eagle Master rank. Good K/D stats. Email changeable, 30-day warranty.'
    },
    media: [
      { emoji: '🎯', type: 'video', dur: '0:58' },
      { emoji: '🔫', type: 'img' },
      { emoji: '🔪', type: 'img' },
      { emoji: '🏅', type: 'img' },
    ],
  },
  {
    id: 3,
    title: { ru: 'Epic Games + Fortnite', en: 'Epic Games + Fortnite' },
    short: { ru: 'Скины, батл-пасс активен', en: 'Skins, battle pass active' },
    platform: 'Epic Games',
    genres: ['shooter'],
    type: ['skins', 'games'],
    region: 'cis',
    price: 10.99,
    oldPrice: null,
    rating: 4.6,
    reviews: 156,
    sold: 245,
    added: 8,
    updated: 5,
    emoji: '🏆',
    gradient: ['#0D47A1', '#1976D2'],
    badge: 'new',
    features: {
      ru: ['23 скина (Renegade Raider)', 'Батл-пасс текущего сезона', 'ВБ на 2800'],
      en: ['23 skins (Renegade Raider)', 'Current season battle pass', '2800 V-Bucks'],
    },
    desc: {
      ru: 'Аккаунт Fortnite с коллекцией из 23 скинов — включая редкий Renegade Raider из первого сезона. Батл-пасс текущего сезона разблокирован, на балансе 2800 ВБ. Родной email в комплекте, привязок к соцсетям нет.',
      en: 'Fortnite account with 23 skins — including rare Renegade Raider from season one. Current battle pass unlocked, 2800 V-Bucks balance. Original email included, no social links.'
    },
    media: [
      { emoji: '🏆', type: 'video', dur: '1:10' },
      { emoji: '🎪', type: 'img' },
      { emoji: '🪂', type: 'img' },
      { emoji: '💎', type: 'img' },
    ],
  },
  {
    id: 4,
    title: { ru: 'Dota 2 — Immortal', en: 'Dota 2 — Immortal' },
    short: { ru: '6 200 MMR, редкие арканы', en: '6,200 MMR, rare arcanas' },
    platform: 'Steam',
    genres: ['moba'],
    type: ['rank', 'skins'],
    region: 'ru',
    price: 41.99,
    oldPrice: null,
    rating: 4.7,
    reviews: 98,
    sold: 134,
    added: 6,
    updated: 2,
    emoji: '⚔️',
    gradient: ['#B71C1C', '#E64A19'],
    badge: 'new',
    features: {
      ru: ['Immortal · 6 200 MMR', '5 арканов (Kunkka, Invoker)', '100+ курьеров'],
      en: ['Immortal · 6,200 MMR', '5 arcanas (Kunkka, Invoker)', '100+ couriers'],
    },
    desc: {
      ru: 'Профессионально прокачанный аккаунт Dota 2: рейтинг Immortal, 6 200 MMR. В инвентаре 5 арканных предметов (Kunkka «Меч глубин», Invoker «Каменный хаос» и другие), 100+ курьеров, редкие чаты. Winrate за сезон 58%. Полный доступ, почта сменяемая.',
      en: 'Professionally leveled Dota 2 account: Immortal rank, 6,200 MMR. 5 arcana items (Kunkka, Invoker and more), 100+ couriers, rare chat wheels. 58% seasonal winrate. Full access, email changeable.'
    },
    media: [
      { emoji: '⚔️', type: 'video', dur: '2:05' },
      { emoji: '🔮', type: 'img' },
      { emoji: '🏆', type: 'img' },
      { emoji: '📊', type: 'img' },
    ],
  },
  {
    id: 5,
    title: { ru: 'Valorant — все агенты', en: 'Valorant — All Agents' },
    short: { ru: '23 агента, 5 скинов', en: '23 agents, 5 skins' },
    platform: 'Riot',
    genres: ['shooter'],
    type: ['games'],
    region: 'eu',
    price: 21.49,
    oldPrice: 28.99,
    rating: 4.5,
    reviews: 76,
    sold: 92,
    added: 5,
    updated: 4,
    emoji: '🔫',
    gradient: ['#BF360C', '#FF7043'],
    badge: 'new',
    features: {
      ru: ['Все 23 агента открыты', 'Скины: Prime, Reaver', 'Ранг Diamond 2'],
      en: ['All 23 agents unlocked', 'Skins: Prime, Reaver', 'Diamond 2 rank'],
    },
    desc: {
      ru: 'Аккаунт Valorant со всеми открытыми агентами и коллекцией скинов (Prime Vandal, Reaver Phantom). Текущий ранг Diamond 2, до Immortal один ранкед. Аккаунт регион EU, без привязки к телефону — добавите свой.',
      en: 'Valorant account with all agents and skin collection (Prime Vandal, Reaver Phantom). Current rank Diamond 2, one ranked game to Immortal. EU region, no phone linked — add yours.'
    },
    media: [
      { emoji: '🔫', type: 'video', dur: '1:32' },
      { emoji: '🎯', type: 'img' },
      { emoji: '💠', type: 'img' },
      { emoji: '📜', type: 'img' },
    ],
  },
  {
    id: 6,
    title: { ru: 'GTA V Premium + GTA$', en: 'GTA V Premium + GTA$' },
    short: { ru: '$10M на балансе Online', en: '$10M Online balance' },
    platform: 'Rockstar',
    genres: ['racing', 'shooter'],
    type: ['games'],
    region: 'ru',
    price: 18.99,
    oldPrice: 29.99,
    rating: 4.8,
    reviews: 243,
    sold: 387,
    added: 30,
    updated: 7,
    emoji: '🚗',
    gradient: ['#1B5E20', '#43A047'],
    badge: 'hot',
    features: {
      ru: ['$10M GTA$ на балансе', 'Уровень 120', 'Бизнесы и терминал'],
      en: ['$10M GTA$ balance', 'Level 120', 'Businesses and Terminal'],
    },
    desc: {
      ru: 'Аккаунт GTA V с Premium Edition: на балансе Online $10 миллионов, уровень персонажа 120, открыты все бизнесы (моторпул, терминал, ночные клубы). Гараж на 20 машин, редкие vehicles. Полный доступ к Rockstar Games Social Club.',
      en: 'GTA V Premium Edition account: $10M Online balance, level 120 character, all businesses unlocked (motorpool, terminal, nightclubs). 20-car garage, rare vehicles. Full Rockstar Games Social Club access.'
    },
    media: [
      { emoji: '🚗', type: 'video', dur: '1:47' },
      { emoji: '🌴', type: 'img' },
      { emoji: '🚁', type: 'img' },
      { emoji: '💰', type: 'img' },
    ],
  },
  {
    id: 7,
    title: { ru: 'Rust + все DLC', en: 'Rust + All DLC' },
    short: { ru: '4200 часов, 15 скинов', en: '4,200 hours, 15 skins' },
    platform: 'Steam',
    genres: ['shooter', 'sim'],
    type: ['games', 'skins'],
    region: 'eu',
    price: 25.99,
    oldPrice: null,
    rating: 4.7,
    reviews: 132,
    sold: 178,
    added: 45,
    updated: 2,
    emoji: '⛏️',
    gradient: ['#37474F', '#607D8B'],
    badge: 'hot',
    features: {
      ru: ['4200+ часов в игре', '15 скинов (Hazard, Punishment)', 'Clean, без банов'],
      en: ['4,200+ hours played', '15 skins (Hazard, Punishment)', 'Clean, no bans'],
    },
    desc: {
      ru: 'Аккаунт Rust с огромным наигранным временем (4200+ часов) и коллекцией из 15 скинов, включая набор Hazard Suit и Punishment Mask. VAC-банов нет, игра куплена легально. Идеален для тех, кто не хочет начинать с нуля.',
      en: 'Rust account with massive playtime (4,200+ hours) and 15 skins including Hazard Suit and Punishment Mask sets. No VAC bans, legally purchased. Perfect for players who want to skip the grind.'
    },
    media: [
      { emoji: '⛏️', type: 'video', dur: '2:18' },
      { emoji: '🏚️', type: 'img' },
      { emoji: '🔥', type: 'img' },
      { emoji: '🪓', type: 'img' },
    ],
  },
  {
    id: 8,
    title: { ru: 'Apex Legends + легенды', en: 'Apex Legends + Legends' },
    short: { ru: 'Diamond, 19 легенд', en: 'Diamond, 19 legends' },
    platform: 'Origin',
    genres: ['shooter'],
    type: ['rank', 'skins'],
    region: 'cis',
    price: 11.99,
    oldPrice: 17.99,
    rating: 4.4,
    reviews: 88,
    sold: 121,
    added: 25,
    updated: 6,
    emoji: '🎭',
    gradient: ['#880E4F', '#C2185B'],
    badge: 'hot',
    features: {
      ru: ['Ранг Diamond', '19 легенд открыто', '40+ скинов'],
      en: ['Diamond rank', '19 legends unlocked', '40+ skins'],
    },
    desc: {
      ru: 'Аккаунт Apex Legends: ранг Diamond, открыто 19 легенд из 20. Коллекция из 40+ скинов, включая наследие Wraith. Battle Pass прошлых сезонов частично прокачан. Origin email в комплекте.',
      en: 'Apex Legends account: Diamond rank, 19 of 20 legends unlocked. 40+ skins including Wraith heirloom. Previous battle passes partially progressed. Origin email included.'
    },
    media: [
      { emoji: '🎭', type: 'video', dur: '1:15' },
      { emoji: '⚡', type: 'img' },
      { emoji: '🎖️', type: 'img' },
      { emoji: '🔫', type: 'img' },
    ],
  },
  {
    id: 9,
    title: { ru: 'Minecraft Java + Bedrock', en: 'Minecraft Java + Bedrock' },
    short: { ru: 'Полный доступ, смена ника', en: 'Full access, name change' },
    platform: 'Mojang',
    genres: ['sim'],
    type: ['games'],
    region: 'ru',
    price: 14.49,
    oldPrice: null,
    rating: 4.9,
    reviews: 301,
    sold: 456,
    added: 60,
    updated: 10,
    emoji: '🏰',
    gradient: ['#33691E', '#689F38'],
    badge: 'hot',
    features: {
      ru: ['Java + Bedrock Editions', 'Смена ника доступна', 'Без банов на серверах'],
      en: ['Java + Bedrock Editions', 'Name change available', 'No server bans'],
    },
    desc: {
      ru: 'Аккаунт Minecraft с обеими версиями: Java Edition и Bedrock. Ник всегда можно сменить (история ников чистая). Миграция на Microsoft учётку уже сделана. Серверных банов нет, покупка оригинальная.',
      en: 'Minecraft account with both editions: Java and Bedrock. Nickname changeable (clean history). Microsoft migration already done. No server bans, original purchase.'
    },
    media: [
      { emoji: '🏰', type: 'video', dur: '0:55' },
      { emoji: '🧱', type: 'img' },
      { emoji: '⛏️', type: 'img' },
      { emoji: '🐑', type: 'img' },
    ],
  },
  {
    id: 10,
    title: { ru: 'FC 24 + Ultimate Team', en: 'FC 24 + Ultimate Team' },
    short: { ru: '850K монет, топ-игроки', en: '850K coins, top players' },
    platform: 'EA',
    genres: ['sim', 'racing'],
    type: ['games', 'skins'],
    region: 'eu',
    price: 34.99,
    oldPrice: 47.99,
    rating: 4.3,
    reviews: 67,
    sold: 89,
    added: 20,
    updated: 8,
    emoji: '⚽',
    gradient: ['#00695C', '#26A69A'],
    badge: 'hot',
    features: {
      ru: ['850K монет UT', 'Mbappe, Haaland в клубе', 'Div 3 ранг'],
      en: ['850K UT coins', 'Mbappe, Haaland in club', 'Div 3 rank'],
    },
    desc: {
      ru: 'Аккаунт EA FC 24 с прокачанным Ultimate Team: 850 тысяч монет на балансе, в клубе Mbappe, Haaland, Modrić. Division 3 в FUT Champions. Аккаунт чистый, без санкций EA.',
      en: 'EA FC 24 account with developed Ultimate Team: 850K coins balance, Mbappe, Haaland, Modrić in club. Division 3 in FUT Champions. Clean account, no EA sanctions.'
    },
    media: [
      { emoji: '⚽', type: 'video', dur: '1:20' },
      { emoji: '🏟️', type: 'img' },
      { emoji: '🥇', type: 'img' },
      { emoji: '📋', type: 'img' },
    ],
  },
  {
    id: 11,
    title: { ru: 'The Witcher 3 Complete', en: 'The Witcher 3 Complete' },
    short: { ru: 'Все DLC, 118 часов', en: 'All DLC, 118 hours' },
    platform: 'Steam',
    genres: ['rpg'],
    type: ['games'],
    region: 'ru',
    price: 9.49,
    oldPrice: null,
    rating: 4.9,
    reviews: 178,
    sold: 234,
    added: 90,
    updated: 15,
    emoji: '🗡️',
    gradient: ['#4A148C', '#673AB7'],
    badge: null,
    features: {
      ru: ['Все DLC (Blood & Wine)', '118 ч наиграно', 'Достижения ×45'],
      en: ['All DLC (Blood & Wine)', '118 hrs played', '45 achievements'],
    },
    desc: {
      ru: 'The Witcher 3: Wild Hunt — Complete Edition со всеми дополнениями (Hearts of Stone, Blood & Wine). Наиграно 118 часов, получено 45 достижений. Аккаунт чистый, без VAC-банов.',
      en: 'The Witcher 3: Wild Hunt — Complete Edition with all DLC (Hearts of Stone, Blood & Wine). 118 hours played, 45 achievements. Clean account, no bans.'
    },
    media: [
      { emoji: '🗡️', type: 'video', dur: '1:55' },
      { emoji: '🐺', type: 'img' },
      { emoji: '🧙', type: 'img' },
      { emoji: '🗺️', type: 'img' },
    ],
  },
  {
    id: 12,
    title: { ru: 'Cyberpunk 2077 + PL', en: 'Cyberpunk 2077 + PL' },
    short: { ru: 'Phantom Liberty включено', en: 'Phantom Liberty included' },
    platform: 'Steam',
    genres: ['rpg', 'shooter'],
    type: ['games'],
    region: 'eu',
    price: 17.99,
    oldPrice: null,
    rating: 4.7,
    reviews: 145,
    sold: 198,
    added: 35,
    updated: 9,
    emoji: '🌐',
    gradient: ['#0D47A1', '#FFC107'],
    badge: null,
    features: {
      ru: ['Phantom Liberty DLC', '56 ч наиграно', 'Редкие импланты'],
      en: ['Phantom Liberty DLC', '56 hrs played', 'Rare cyberware'],
    },
    desc: {
      ru: 'Cyberpunk 2077 с дополнением Phantom Liberty. Наиграно 56 часов, персонаж с редкими имплантами и прокачкой. Аккаунт Steam, куплен легально, без банов.',
      en: 'Cyberpunk 2077 with Phantom Liberty expansion. 56 hours played, character with rare cyberware and progression. Steam account, legally purchased, no bans.'
    },
    media: [
      { emoji: '🌐', type: 'video', dur: '2:30' },
      { emoji: '🌆', type: 'img' },
      { emoji: '🤖', type: 'img' },
      { emoji: '🚗', type: 'img' },
    ],
  },
  {
    id: 13,
    title: { ru: "Baldur's Gate 3 Deluxe", en: "Baldur's Gate 3 Deluxe" },
    short: { ru: 'Цифровое издание Deluxe', en: 'Digital Deluxe Edition' },
    platform: 'Steam',
    genres: ['rpg'],
    type: ['games'],
    region: 'ru',
    price: 35.99,
    oldPrice: null,
    rating: 5.0,
    reviews: 210,
    sold: 267,
    added: 50,
    updated: 12,
    emoji: '🐉',
    gradient: ['#827717', '#C0CA33'],
    badge: null,
    features: {
      ru: ['Deluxe Edition контент', '12 ч наиграно', 'Divinity-предметы'],
      en: ['Deluxe Edition content', '12 hrs played', 'Divinity items'],
    },
    desc: {
      ru: "Baldur's Gate 3 Digital Deluxe Edition с бонусным контентом (Divinity-предметы, маска дракона). Наиграно 12 часов, начало компании. Один из лучших RPG последних лет — играйте сразу.",
      en: "Baldur's Gate 3 Digital Deluxe Edition with bonus content (Divinity items, dragon mask). 12 hours played, early campaign. One of the best RPGs in years — play right away."
    },
    media: [
      { emoji: '🐉', type: 'video', dur: '2:45' },
      { emoji: '🧝', type: 'img' },
      { emoji: '🔮', type: 'img' },
      { emoji: '⚔️', type: 'img' },
    ],
  },
  {
    id: 14,
    title: { ru: 'Starfield Premium', en: 'Starfield Premium' },
    short: { ru: 'Game Pass не привязан', en: 'Game Pass not linked' },
    platform: 'Xbox',
    genres: ['rpg', 'sim'],
    type: ['games'],
    region: 'cis',
    price: 41.99,
    oldPrice: 56.99,
    rating: 4.2,
    reviews: 54,
    sold: 67,
    added: 40,
    updated: 11,
    emoji: '🚀',
    gradient: ['#263238', '#546E7A'],
    badge: null,
    features: {
      ru: ['Premium Edition', 'Constellation-контент', '8 ч наиграно'],
      en: ['Premium Edition', 'Constellation content', '8 hrs played'],
    },
    desc: {
      ru: 'Starfield Premium Edition с контентом Constellation. Game Pass не привязан — полный контроль. Наиграно 8 часов, начало сюжета. Xbox/PC — играйте где удобно.',
      en: 'Starfield Premium Edition with Constellation content. Game Pass not linked — full control. 8 hours played, early story. Xbox/PC — play anywhere.'
    },
    media: [
      { emoji: '🚀', type: 'video', dur: '1:40' },
      { emoji: '🪐', type: 'img' },
      { emoji: '🛸', type: 'img' },
      { emoji: '👨‍🚀', type: 'img' },
    ],
  },
  {
    id: 15,
    title: { ru: 'Skull and Bones', en: 'Skull and Bones' },
    short: { ru: 'Почта сменяемая', en: 'Email changeable' },
    platform: 'Ubisoft',
    genres: ['sim', 'shooter'],
    type: ['games'],
    region: 'eu',
    price: 25.99,
    oldPrice: null,
    rating: 3.9,
    reviews: 41,
    sold: 52,
    added: 15,
    updated: 14,
    emoji: '🏴‍☠️',
    gradient: ['#01579B', '#0288D1'],
    badge: null,
    features: {
      ru: ['Стандартное издание', 'Почта сменяемая', 'Ubisoft Connect'],
      en: ['Standard edition', 'Email changeable', 'Ubisoft Connect'],
    },
    desc: {
      ru: 'Skull and Bones — морской пиратский симулятор от Ubisoft. Стандартное издание, почта сменяемая, привязка к Ubisoft Connect. Полный доступ.',
      en: 'Skull and Bones — naval pirate simulator from Ubisoft. Standard edition, email changeable, Ubisoft Connect linked. Full access.'
    },
    media: [
      { emoji: '🏴‍☠️', type: 'video', dur: '1:25' },
      { emoji: '⛵', type: 'img' },
      { emoji: '🌊', type: 'img' },
      { emoji: '💀', type: 'img' },
    ],
  },
];

/* Баннеры для главной (как в Steam) */
const BANNERS = [
  { gameId: 1,  headline: { ru: 'Прокачанный Steam + 50 игр', en: 'Leveled Steam + 50 games' }, sub: { ru: 'CS2 Prime · GTA V · Rust · Elden Ring', en: 'CS2 Prime · GTA V · Rust · Elden Ring' } },
  { gameId: 4,  headline: { ru: 'Dota 2 Immortal · 6 200 MMR', en: 'Dota 2 Immortal · 6,200 MMR' }, sub: { ru: '5 арканов · редкие курьеры', en: '5 arcanas · rare couriers' } },
  { gameId: 6,  headline: { ru: 'GTA V Premium · $10M Online', en: 'GTA V Premium · $10M Online' }, sub: { ru: 'Уровень 120 · все бизнесы', en: 'Level 120 · all businesses' } },
  { gameId: 2,  headline: { ru: 'CS2 Prime · AK Redline + нож', en: 'CS2 Prime · AK Redline + knife' }, sub: { ru: 'Ранг Legendary Eagle', en: 'Legendary Eagle rank' } },
  { gameId: 13, headline: { ru: "Baldur's Gate 3 Deluxe", en: "Baldur's Gate 3 Deluxe" }, sub: { ru: 'Игра года · Digital Deluxe', en: 'Game of the Year · Digital Deluxe' } },
];

/* Справочники для фильтров (i18n) */
const PLATFORMS = ['Steam', 'Epic Games', 'Rockstar', 'Riot', 'Origin', 'EA', 'Mojang', 'Xbox', 'Ubisoft'];
const GENRES = {
  shooter: { ru: 'Шутеры', en: 'Shooters' },
  moba:    { ru: 'MOBA',    en: 'MOBA' },
  rpg:     { ru: 'RPG',     en: 'RPG' },
  sim:     { ru: 'Симуляторы', en: 'Simulators' },
  racing:  { ru: 'Гонки',   en: 'Racing' },
};
const TYPES = {
  games: { ru: 'С играми', en: 'With games' },
  skins: { ru: 'Со скинами', en: 'With skins' },
  rank:  { ru: 'С рангом', en: 'With rank' },
  empty: { ru: 'Пустой', en: 'Empty' },
};
const REGIONS = {
  ru:  { ru: 'Россия', en: 'Russia' },
  cis: { ru: 'СНГ', en: 'CIS' },
  eu:  { ru: 'Европа', en: 'Europe' },
  other: { ru: 'Другое', en: 'Other' },
};

/* Steam CDN обложки (публичный CDN Valve, библиотечные капсулы 600x900) */
const STEAM_ART = {
  cs2: 730, gta5: 271590, rust: 252490, dota2: 570,
  witcher3: 292030, cyberpunk: 1091500, bg3: 1086940,
  starfield: 1716740, apex: 1172470, ea_fc: 2195250,
};
const steamCapsule = appid => `https://cdn.cloudflare.steamstatic.com/steam/apps/${appid}/library_600x900.jpg`;

/* Обложка для карточки: у игр с известным appid — реальный арт, иначе градиент+эмодзи */
const ART_BY_ID = {
  2: 'cs2', 6: 'gta5', 7: 'rust', 4: 'dota2',
  11: 'witcher3', 12: 'cyberpunk', 13: 'bg3', 14: 'starfield',
  8: 'apex', 10: 'ea_fc',
};
